spring:
  data:
    mongodb:
      uri: mongodb+srv://dnolavo:c2KutMEuFCvodPM3@cluster0.ie36z.mongodb.net/
      database: myDatabase
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG